image: ubuntu/focal
packages:
  - build-essential
  - clang-10
  - clang-format
  - valgrind
  - xsltproc
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      make test MEMCHECK=yes OPT=-O3 SANITIZE=undefined CC=clang-10 -j$(nproc)
  - build: |
      cd kefir
      make clean
      make all OPT=-O3 CC=clang-10
triggers:
  - action: email
    condition: failure
    to: jprotopopov1122@gmail.com
